export const TOGGLE_CART_MODAL = "TOGGLE_CART_MODAL";
export const CLOSE_CART_MODAL = "CLOSE_CART_MODAL";
export const ADD_ITEM = "ADD_ITEM";
export const REMOVE_ITEM = "REMOVE_ITEM";
export const REDUCE_ITEM_QUANTITY = "REDUCE_ITEM_QUANTITY";
export const CLEAR_CART = "CLEAR_CART";

export const TOGGLE_CURRENCY_MODAL = "TOGGLE_CURRENCY_MODAL";
export const CLOSE_CURRENCY_MODAL = "CLOSE_CURRENCY_MODAL";
export const SET_CURRENCIES = "SET_CURRENCIES";
export const CHANGE_CURRENCY = "CHANGE_CURRENCY";
export const CHANGE_AMOUNT = "CHANGE_CURRENCY";
